/**
 * Local fallback menu — Gringos Cubanos. Sheet CSV can override when URLs are set.
 * TODO: Confirm bottled water, lemon garlic oil add-on, and dessert pricing when owner finalizes.
 */
import { gallerySrc } from "@/lib/data/gallery-path";
import type { MenuItem } from "./schema";

export const localMenuItems: MenuItem[] = [
  {
    id: "sandwich-cuban",
    active: true,
    category: "Sandwiches",
    sortOrder: 1,
    name: "Cuban",
    description:
      "Marinated Cuban pulled pork, sliced ham, and swiss cheese topped with mayo, yellow mustard, onions, and pickles.",
    price: 15,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food13*****.jpg"),
    imageAlt: "Cuban sandwich — Gringos Cubanos",
  },
  {
    id: "sandwich-chicken-cuban",
    active: true,
    category: "Sandwiches",
    sortOrder: 2,
    name: "Chicken Cuban",
    description:
      "Marinated Cuban shredded chicken, sliced ham, and swiss cheese topped with mayo, yellow mustard, onions, and pickles.",
    price: 15,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food22******.jpg"),
    imageAlt: "Chicken Cuban sandwich",
  },
  {
    id: "sandwich-cuban-steak",
    active: true,
    category: "Sandwiches",
    sortOrder: 3,
    name: "Cuban Steak",
    description:
      "Marinated Cuban steak and grilled onions, crowned with crispy potato sticks.",
    price: 17,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food20*****8.jpg"),
    imageAlt: "Cuban steak sandwich",
  },
  {
    id: "sandwich-fritas",
    active: true,
    category: "Sandwiches",
    sortOrder: 4,
    name: "Fritas",
    description:
      "Blend of beef and chorizo burger topped with cheese, grilled onions, and potato sticks. Add an extra patty from Sides.",
    price: 10,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food21****.jpg"),
    imageAlt: "Fritas sandwich",
  },
  {
    id: "side-empanada-single",
    active: true,
    category: "Sides",
    sortOrder: 1,
    name: "Beef Empanada (single)",
    description: "Crispy beef empanada.",
    price: 5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food12****.jpg"),
    imageAlt: "Beef empanada",
  },
  {
    id: "side-empanada-two",
    active: true,
    category: "Sides",
    sortOrder: 2,
    name: "Beef Empanadas (2 for $8)",
    description: "Two crispy beef empanadas.",
    price: 8,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food24****.jpg"),
    imageAlt: "Beef empanadas",
  },
  {
    id: "side-beans-rice",
    active: true,
    category: "Sides",
    sortOrder: 3,
    name: "Black Beans & Rice",
    description: "Classic Cuban-style beans and rice.",
    price: 5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food3.jpg"),
    imageAlt: "Black beans and rice",
  },
  {
    id: "side-tostones",
    active: true,
    category: "Sides",
    sortOrder: 4,
    name: "Tostones / Fried Plantains",
    description:
      "Crispy fried plantains. Add homemade lemon garlic oil for extra flavor (see add-on — price TBD).",
    price: 7,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food8.jpg"),
    imageAlt: "Tostones fried plantains",
  },
  {
    id: "side-fries",
    active: true,
    category: "Sides",
    sortOrder: 5,
    name: "Fresh Hand-Cut Fries",
    description: "Hand-cut fries, hot and crisp.",
    price: 5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food4.jpg"),
    imageAlt: "Hand-cut fries",
  },
  {
    id: "side-fritas-extra-patty",
    active: true,
    category: "Sides",
    sortOrder: 6,
    name: "Extra patty (for Fritas)",
    description: "Add a second patty to your Fritas order.",
    price: 5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food26****.jpg"),
    imageAlt: "Extra patty add-on",
  },
  {
    id: "side-lemon-garlic-oil",
    active: true,
    category: "Sides",
    sortOrder: 7,
    name: "Homemade lemon garlic oil (add-on)",
    description:
      "Optional add-on for tostones. TODO: confirm price with owner — currently Price TBD at checkout.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food17.jpg"),
    imageAlt: "Lemon garlic oil add-on",
  },
  {
    id: "bowl-pork",
    active: true,
    category: "Bowls",
    sortOrder: 1,
    name: "Bowl with Pork",
    description: "Hearty bowl with marinated Cuban pork.",
    price: 10,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
    imageUrl: gallerySrc("food5.jpg"),
    imageAlt: "Bowl with pork",
  },
  {
    id: "bowl-chicken",
    active: true,
    category: "Bowls",
    sortOrder: 2,
    name: "Bowl with Chicken",
    description: "Hearty bowl with marinated Cuban chicken.",
    price: 10,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food6.jpg"),
    imageAlt: "Bowl with chicken",
  },
  {
    id: "bowl-steak",
    active: true,
    category: "Bowls",
    sortOrder: 3,
    name: "Bowl with Steak",
    description: "Hearty bowl with marinated Cuban steak.",
    price: 11,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food7.jpg"),
    imageAlt: "Bowl with steak",
  },
  {
    id: "kids-grilled-cheese",
    active: true,
    category: "Kid's Meals",
    sortOrder: 1,
    name: "Grilled Cheese",
    description: "Includes hand-cut fries and a drink.",
    price: 10,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food9.jpg"),
    imageAlt: "Kids grilled cheese meal",
  },
  {
    id: "kids-ham-cheese",
    active: true,
    category: "Kid's Meals",
    sortOrder: 2,
    name: "Ham and Cheese",
    description: "Includes hand-cut fries and a drink.",
    price: 11,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food11.jpg"),
    imageAlt: "Kids ham and cheese meal",
  },
  {
    id: "bev-soda",
    active: true,
    category: "Beverages",
    sortOrder: 1,
    name: "Soda",
    description: "Assorted sodas — ask at the window.",
    price: 2,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food1.jpg"),
    imageAlt: "Soda",
  },
  {
    id: "bev-water",
    active: true,
    category: "Beverages",
    sortOrder: 2,
    name: "Bottled Water",
    description: "TODO: confirm price with owner.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food2.jpg"),
    imageAlt: "Bottled water",
  },
  {
    id: "dessert-ask",
    active: true,
    category: "Desserts",
    sortOrder: 1,
    name: "Ask about our desserts",
    description: "Rotating sweets — ask the team what is available today.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    imageUrl: gallerySrc("food18.jpg"),
    imageAlt: "Desserts at Gringos Cubanos",
  },
];
